Unify variable name style

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -11,14 +11,14 @@ variables:
   DOCKER_TLS_CERTDIR: "" # Work around failing CI jobs: see https://gitlab.com/gitlab-org/gitlab-ce/issues/64959#note_194582424
   FF_SCRIPT_SECTIONS: 'true'  # Enable collapsible sections per script line, with timings
 
-  PROJECT_REGISTRY: ${CI_REGISTRY}/${CI_PROJECT_PATH}
-  IMAGE_TAG: sha-${CI_COMMIT_SHA}
-  IMAGE_TAG_TEST: sha-test-${CI_COMMIT_SHA}
-  PARENT_IMAGE_TAG: sha-test-${CI_COMMIT_BEFORE_SHA}
+  PROJECT_REGISTRY: $CI_REGISTRY/$CI_PROJECT_PATH
+  IMAGE_TAG: sha-$CI_COMMIT_SHA
+  IMAGE_TAG_TEST: sha-test-$CI_COMMIT_SHA
+  PARENT_IMAGE_TAG: sha-test-$CI_COMMIT_BEFORE_SHA
 
   CORE_PROJECT: pep/core
   # Override to set branch/ref of pep/core to test images on
-  CORE_TEST_REF: ${CI_COMMIT_BRANCH}
+  CORE_TEST_REF: $CI_COMMIT_BRANCH
 
   FORCE_TEST:
     value: ''
@@ -83,21 +83,21 @@ workflow:
     - docker-small
   image: docker
   variables:
-    CONTAINER_IMAGE: ${PROJECT_REGISTRY}/${IMAGE_KIND}-${IMAGE_NAME}:${IMAGE_TAG_TEST}
+    CONTAINER_IMAGE: $PROJECT_REGISTRY/$IMAGE_KIND-$IMAGE_NAME:$IMAGE_TAG_TEST
   services:
     - docker:dind
   <<: *rules_only_when_building
   before_script:
     - apk add --no-cache jq coreutils  # Also add coreutils for `date` (Alpine/busybox date doesn't parse ISO-8601 well)
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
-    - touch "${CI_PROJECT_DIR}/env.env"
+    - touch "$CI_PROJECT_DIR/env.env"
     - |
-      prev_created=$(docker buildx imagetools inspect ${PROJECT_REGISTRY}/${IMAGE_KIND}-${IMAGE_NAME}:${IMAGE_TAG} --format '{{json .Image}}' | jq --raw-output .created || true)
+      prev_created=$(docker buildx imagetools inspect $PROJECT_REGISTRY/$IMAGE_KIND-$IMAGE_NAME:$IMAGE_TAG --format '{{json .Image}}' | jq --raw-output .created || true)
       if [ -n "$prev_created" ]; then
         diff_secs=$(($(date +%s) - $(date -d "$prev_created" +%s)))
         diff_days=$((diff_secs / 60 / 60 / 24))
         echo "Previous image created at $prev_created, $diff_days days ($diff_secs s) ago"
-        if [ "$diff_days" -lt "${IMAGE_MAX_AGE_DAYS}" ]; then
+        if [ "$diff_days" -lt "$IMAGE_MAX_AGE_DAYS" ]; then
           echo "Recent enough, won't rebuild"
           exit
         else
@@ -106,7 +106,7 @@ workflow:
       else
         echo 'No existing image for this commit'
       fi
-      echo 'NEW_IMAGE=yes' >>"${CI_PROJECT_DIR}/env.env"  # Save, see artifacts
+      echo 'NEW_IMAGE=yes' >>"$CI_PROJECT_DIR/env.env"  # Save, see artifacts
     - echo "Tagging image as $CONTAINER_IMAGE"
   script:
     - echo '==== Building & pushing image ===='
@@ -114,10 +114,10 @@ workflow:
       docker buildx build
       --pull
       --push
-      --file ./${IMAGE_KIND}/${IMAGE_NAME}.Dockerfile
-      --tag ${CONTAINER_IMAGE}
-      ${DOCKER_ARGS}
-      ./${IMAGE_KIND}/
+      --file ./$IMAGE_KIND/$IMAGE_NAME.Dockerfile
+      --tag $CONTAINER_IMAGE
+      $DOCKER_ARGS
+      ./$IMAGE_KIND/
   artifacts:
     reports:
       # Save $NEW_IMAGE for jobs below
@@ -156,7 +156,7 @@ runtime/ubuntu-2204:
   <<: *rules_only_when_building
   # This script must work with both bash and powershell
   script:
-    - cd ./${IMAGE_KIND}/conan/
+    - cd ./$IMAGE_KIND/conan/
     - >
       conan lock create ./ --update
       --profile:all=./conan_profile
@@ -181,16 +181,16 @@ runtime/ubuntu-2204:
       conan lock merge
       --lockfile=./conan-rel.lock
       --lockfile=./conan-dbg.lock
-      --lockfile-out=./conan.${name}.lock
+      --lockfile-out=./conan.$name.lock
   artifacts:
     paths:
-      - ./${IMAGE_KIND}/conan/conan.${name}.lock
+      - ./$IMAGE_KIND/conan/conan.$name.lock
 
 .generate-lockfile-docker:
   extends: .generate-lockfile
   tags:
     - docker-small
-  image: ${PROJECT_REGISTRY}/builder-${name}:${IMAGE_TAG_TEST}
+  image: $PROJECT_REGISTRY/builder-$name:$IMAGE_TAG_TEST
 
 builder/lockfile/ubuntu-2204:
   extends: .generate-lockfile-docker
@@ -243,12 +243,12 @@ merge-lockfiles:
     IMAGE_KIND: builder
   tags:
     - docker-small
-  image: ${PROJECT_REGISTRY}/builder-ubuntu-2204:${IMAGE_TAG_TEST}
+  image: $PROJECT_REGISTRY/builder-ubuntu-2204:$IMAGE_TAG_TEST
   <<: *rules_only_when_building
   script:
     - *git_colors
-    - echo "MERGE_LOCKFILES_JOB=${CI_JOB_ID}" >>"${CI_PROJECT_DIR}/env.env"  # Save, see artifacts
-    - cd ./${IMAGE_KIND}/conan/
+    - echo "MERGE_LOCKFILES_JOB=$CI_JOB_ID" >>"$CI_PROJECT_DIR/env.env"  # Save, see artifacts
+    - cd ./$IMAGE_KIND/conan/
     - jobs=(
         ubuntu-2204
         ubuntu-rolling
@@ -266,11 +266,11 @@ merge-lockfiles:
     - >
       git diff --exit-code ./conan.lock
       && echo 'conan.lock did not change'
-      || echo 'LOCKFILE_CHANGED=yes' >>"${CI_PROJECT_DIR}/env.env"  # Save if changed, see artifacts
+      || echo 'LOCKFILE_CHANGED=yes' >>"$CI_PROJECT_DIR/env.env"  # Save if changed, see artifacts
     - cp ./conan.lock ../../
   artifacts:
     paths:
-      - ./${IMAGE_KIND}/conan/conan.lock
+      - ./$IMAGE_KIND/conan/conan.lock
       - ./conan.lock
     reports:
       # Save $MERGE_LOCKFILES_JOB, $LOCKFILE_CHANGED for jobs below
@@ -287,34 +287,34 @@ merge-lockfiles:
   <<: *rules_only_when_building
   variables:
     IMAGE_KIND: builder
-    CONTAINER_IMAGE: ${PROJECT_REGISTRY}/${IMAGE_KIND}-${IMAGE_NAME}:${IMAGE_TAG_TEST}
+    CONTAINER_IMAGE: $PROJECT_REGISTRY/$IMAGE_KIND-$IMAGE_NAME:$IMAGE_TAG_TEST
   services:
     - docker:dind
   script:
     - *set_concurrency_limit
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - echo '==== Executing Conan in container ===='
-    - container="$(docker container run --pull=always --interactive --detach ${CONTAINER_IMAGE})"
+    - container="$(docker container run --pull=always --interactive --detach $CONTAINER_IMAGE)"
     - |
-      if [ -d ./${IMAGE_KIND}/cache/conan-home/ ]; then
+      if [ -d ./$IMAGE_KIND/cache/conan-home/ ]; then
         echo 'Copying cached .conan2 folder'
-        docker cp ./${IMAGE_KIND}/cache/conan-home/ "$container:/root/.conan2/"
+        docker cp ./$IMAGE_KIND/cache/conan-home/ "$container:/root/.conan2/"
       fi
-    - docker container cp ./${IMAGE_KIND}/conan/ "$container:/tmp/conan"
+    - docker container cp ./$IMAGE_KIND/conan/ "$container:/tmp/conan"
     - docker container exec "$container" /tmp/conan/conan_install.sh "$concurrency_limit"
     - docker container exec "$container" rm -rf '/tmp/*'
-    - rm -rf ./${IMAGE_KIND}/cache/conan-home/
-    - mkdir -p ./${IMAGE_KIND}/cache/
-    - docker container cp "$container:/root/.conan2/" ./${IMAGE_KIND}/cache/conan-home
+    - rm -rf ./$IMAGE_KIND/cache/conan-home/
+    - mkdir -p ./$IMAGE_KIND/cache/
+    - docker container cp "$container:/root/.conan2/" ./$IMAGE_KIND/cache/conan-home
     - docker container stop "$container"
-    - docker container commit --message 'Add Conan packages' "$container" ${CONTAINER_IMAGE}
+    - docker container commit --message 'Add Conan packages' "$container" $CONTAINER_IMAGE
 
     - echo "==== Pushing image ===="
-    - docker push ${CONTAINER_IMAGE}
+    - docker push $CONTAINER_IMAGE
   cache:
     key: docker-builder-cache
     paths:
-      - ./${IMAGE_KIND}/cache/
+      - ./$IMAGE_KIND/cache/
 
 builder/ubuntu-2204:
   extends: .conan-builder
@@ -337,7 +337,7 @@ builder/flatpak:
   variables:
     IMAGE_KIND: builder
     IMAGE_NAME: flatpak
-    CONTAINER_IMAGE: ${PROJECT_REGISTRY}/${IMAGE_KIND}-${IMAGE_NAME}:${IMAGE_TAG_TEST}
+    CONTAINER_IMAGE: $PROJECT_REGISTRY/$IMAGE_KIND-$IMAGE_NAME:$IMAGE_TAG_TEST
   services:
     - docker:dind
   script:
@@ -345,10 +345,10 @@ builder/flatpak:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - echo '==== Executing Flatpak Builder with Conan in container ===='
     # --privileged is necessary for flatpak-builder, see https://github.com/flatpak/flatpak-builder/issues/237
-    - container="$(docker container run --pull=always --privileged --interactive --detach ${CONTAINER_IMAGE})"
+    - container="$(docker container run --pull=always --privileged --interactive --detach $CONTAINER_IMAGE)"
     #TODO Cache ~/.conan2 like above?
-    - docker container cp ./${IMAGE_KIND}/flatpak/ "$container:/tmp/flatpak"
-    - docker container cp ./${IMAGE_KIND}/conan/ "$container:/tmp/conan"
+    - docker container cp ./$IMAGE_KIND/flatpak/ "$container:/tmp/flatpak"
+    - docker container cp ./$IMAGE_KIND/conan/ "$container:/tmp/conan"
     - |
       if [ -n "$concurrency_limit" ]; then
         concurrency_option="--jobs=$concurrency_limit"
@@ -358,10 +358,10 @@ builder/flatpak:
     - docker container exec "$container" flatpak build-bundle /tmp/flatpak/repo /pep-base.flatpak nl.ru.cs.pep.base --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
     - docker container exec "$container" rm -rf '/tmp/*'
     - docker container stop "$container"
-    - docker container commit --message 'Build base flatpak with Conan packages' "$container" ${CONTAINER_IMAGE}
+    - docker container commit --message 'Build base flatpak with Conan packages' "$container" $CONTAINER_IMAGE
 
     - echo '==== Pushing image ===='
-    - docker push ${CONTAINER_IMAGE}
+    - docker push $CONTAINER_IMAGE
 
 ###
 test-images:
@@ -377,7 +377,7 @@ test-images:
   image: alpine
   script:
     - apk add --no-cache jq curl
-    - ./run-pipeline.sh ${IMAGE_TAG_TEST} "${CORE_TEST_REF}" "${MERGE_LOCKFILES_JOB}"
+    - ./run-pipeline.sh $IMAGE_TAG_TEST "$CORE_TEST_REF" "$MERGE_LOCKFILES_JOB"
 
 test-images-manual:
   stage: analyze-manual
@@ -389,7 +389,7 @@ test-images-manual:
     # We don't check $NEW_IMAGE here, because we want to make sure that when a commit is added to a different branch,
     #  we run a pipeline in PEP core in the corresponding branch
     - apk add --no-cache jq curl
-    - ./run-pipeline.sh ${IMAGE_TAG} "${CORE_TEST_REF}" "${MERGE_LOCKFILES_JOB}"
+    - ./run-pipeline.sh $IMAGE_TAG "$CORE_TEST_REF" "$MERGE_LOCKFILES_JOB"
 
 ###
 retag-images:
@@ -405,10 +405,10 @@ retag-images:
     - if [ -n "$LOCKFILE_CHANGED" ]; then exit; fi
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - |
-      for image in ${DEPLOY_IMAGES}; do
-        echo "Retagging $image:${IMAGE_TAG_TEST} as ${PROJECT_REGISTRY}/$image:${IMAGE_TAG}"
+      for image in $DEPLOY_IMAGES; do
+        echo "Retagging $image:$IMAGE_TAG_TEST as $PROJECT_REGISTRY/$image:$IMAGE_TAG"
         # This assumes sha-test tags of an image will not be cleaned up if it is still recent and thus reused
-        docker buildx imagetools create --tag ${PROJECT_REGISTRY}/$image:${IMAGE_TAG} ${PROJECT_REGISTRY}/$image:${IMAGE_TAG_TEST}
+        docker buildx imagetools create --tag $PROJECT_REGISTRY/$image:$IMAGE_TAG $PROJECT_REGISTRY/$image:$IMAGE_TAG_TEST
       done
 
 retag-parent-images:
@@ -421,11 +421,11 @@ retag-parent-images:
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - |
-      for image in ${DEPLOY_IMAGES}; do
-        echo "Retagging $image:${PARENT_IMAGE_TAG} as ${PROJECT_REGISTRY}/$image:${IMAGE_TAG_TEST}"
-        docker buildx imagetools create --tag ${PROJECT_REGISTRY}/$image:${IMAGE_TAG_TEST} ${PROJECT_REGISTRY}/$image:${PARENT_IMAGE_TAG}
-        echo "Retagging $image:${PARENT_IMAGE_TAG} as ${PROJECT_REGISTRY}/$image:${IMAGE_TAG}"
-        docker buildx imagetools create --tag ${PROJECT_REGISTRY}/$image:${IMAGE_TAG} ${PROJECT_REGISTRY}/$image:${PARENT_IMAGE_TAG}
+      for image in $DEPLOY_IMAGES; do
+        echo "Retagging $image:$PARENT_IMAGE_TAG as $PROJECT_REGISTRY/$image:$IMAGE_TAG_TEST"
+        docker buildx imagetools create --tag $PROJECT_REGISTRY/$image:$IMAGE_TAG_TEST $PROJECT_REGISTRY/$image:$PARENT_IMAGE_TAG
+        echo "Retagging $image:$PARENT_IMAGE_TAG as $PROJECT_REGISTRY/$image:$IMAGE_TAG"
+        docker buildx imagetools create --tag $PROJECT_REGISTRY/$image:$IMAGE_TAG $PROJECT_REGISTRY/$image:$PARENT_IMAGE_TAG
       done
 
 update-core:
@@ -449,49 +449,49 @@ update-core:
     - *git_colors
     - |
       mkdir -p ~/.ssh
-      >>~/.ssh/known_hosts echo "${CI_SERVER_HOST},131.174.138.131 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDd/zrrJ+9MjUvHBq55u3sdP6Tu+lqA+zCwFDeHtLSl40sOGZvDQ1AE/R6bnQQTSQ+GKUFdwHAar7ePVCBXeDhw="
+      >>~/.ssh/known_hosts echo "$CI_SERVER_HOST,131.174.138.131 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDd/zrrJ+9MjUvHBq55u3sdP6Tu+lqA+zCwFDeHtLSl40sOGZvDQ1AE/R6bnQQTSQ+GKUFdwHAar7ePVCBXeDhw="
       eval $(ssh-agent -s)
-      echo "${SSH_KEY_GITLAB}" | tr -d '\r' | ssh-add -
+      echo "$SSH_KEY_GITLAB" | tr -d '\r' | ssh-add -
       git config --global user.email support@pep.cs.ru.nl
       git config --global user.name 'Gitlab CI script from docker-build'
       rm -rf ./pep
     - >
-      git clone --branch="${CI_COMMIT_REF_NAME}"
+      git clone --branch="$CI_COMMIT_REF_NAME"
       --sparse
       --no-tags
       --depth=1
       --shallow-submodules
       --recurse-submodules=docker-build
-      "git@${CI_SERVER_HOST}:${CORE_PROJECT}.git" ./pep
+      "git@$CI_SERVER_HOST:$CORE_PROJECT.git" ./pep
     - |
       echo 'Updating docker-build'
       (
       cd ./pep/docker-build/
       # Is the commit SHA from this pipeline the head of our branch?
-      if [ "$(git rev-parse "${CI_COMMIT_REF}")" != "${CI_COMMIT_SHA}" ]; then
-        >&2 echo "This (${CI_COMMIT_SHA}) is not the newest docker-build commit"
+      if [ "$(git rev-parse "$CI_COMMIT_REF")" != "$CI_COMMIT_SHA" ]; then
+        >&2 echo "This ($CI_COMMIT_SHA) is not the newest docker-build commit"
         exit 1
       fi
       # Before committing, make sure we are on a branch
-      git checkout "${CI_COMMIT_REF}"
-      mv -f "${CI_PROJECT_DIR}/conan.lock" ./builder/conan/
+      git checkout "$CI_COMMIT_REF"
+      mv -f "$CI_PROJECT_DIR/conan.lock" ./builder/conan/
       git add .
-      git commit -m "Update conan.lock for pipeline ${CI_PIPELINE_ID}
-      ${CI_JOB_URL}"
+      git commit -m "Update conan.lock for pipeline $CI_PIPELINE_ID
+      $CI_JOB_URL"
       git push -o ci.variable='RETAG_PARENT_COMMIT_IMAGES=yes'
-      echo "Made commit at: ${CI_PROJECT_URL}/-/commit/$(git rev-parse HEAD)"
+      echo "Made commit at: $CI_PROJECT_URL/-/commit/$(git rev-parse HEAD)"
       )
     - |
       echo 'Updating core'
       # We just updated the submodule, now update the image tag as well
-      sed --in-place "/s/(RUNNER_IMAGE_TAG:\s*)\S*/\1${IMAGE_TAG}/" ./ci_cd/docker-common.yml
+      sed --in-place "/s/(RUNNER_IMAGE_TAG:\s*)\S*/\1$IMAGE_TAG/" ./ci_cd/docker-common.yml
       if git diff --no-patch --exit-code ./ci_cd/docker-common.yml; then
         # No differences
-        >&2 echo "Failed to update /ci_cd/docker-common.yml in ${CORE_PROJECT}"
+        >&2 echo "Failed to update /ci_cd/docker-common.yml in $CORE_PROJECT"
         exit 1
       fi
       git add .
-      git commit -m "Update docker-build for pipeline ${CI_PIPELINE_ID}
-      ${CI_JOB_URL}"
+      git commit -m "Update docker-build for pipeline $CI_PIPELINE_ID
+      $CI_JOB_URL"
       git push
-      echo "Made commit at: ${CI_SERVER_URL}/${CORE_PROJECT}/-/commit/$(git rev-parse HEAD)"
+      echo "Made commit at: $CI_SERVER_URL/$CORE_PROJECT/-/commit/$(git rev-parse HEAD)"
